# Generated by Django 4.2.2 on 2023-06-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('authentication', '0006_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topics',
            field=models.ManyToManyField(related_name='users', to='topics.topic'),
        ),
    ]
