# Generated by Django 4.2.2 on 2023-06-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='topics',
        ),
    ]
