# Generated by Django 4.2.2 on 2023-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_creator_topic_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(null=True, upload_to='topic_pictures'),
        ),
    ]
